db:
  image: mongo
  ports:
    - "27017:27017"
  command: "--smallfiles --logpath=/dev/null"
web:
  build: ./web
  command: node .
  ports:
    - "80:3000"
  links:
    - db
  expose:
      - "3000"
  environment:
#     VIRTUAL_HOST: services.makeronboard.com
     PORT: 3000
# hostname: services.makeronboard.com
